FROM python:3.14.0rc2-slim-bookworm AS base

WORKDIR /app

USER root

# general requirements: wget
# patchelf requirements: autotools-dev automake build-essential autoconf
# keep after install for builder steps:
#   apt-get: binutils
#   pip: pyinstaller staticx

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget autotools-dev automake build-essential autoconf binutils && \
    wget --no-check-certificate https://github.com/NixOS/patchelf/archive/0.10.tar.gz && \
    tar xzf 0.10.tar.gz && \
    cd patchelf-0.10/ && \
    ./bootstrap.sh && \
    ./configure && \
    make && \
    make clean && \
    make install && \
    cd - && \
    pip install --upgrade pip && \
    pip install pyinstaller staticx && \
    apt-get remove --purge -y wget autotools-dev automake build-essential autoconf && \
    apt-get autoremove -y && apt-get clean
