[package]
name = "checkoff_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = "1.10.0"
matchit = "0.8.6"
tokio = {version= "1", features = ["full"]}
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "mysql"] }
# mimalloc = { version = "0.1.43", features = ["secure"] }
